baseurl = "/"
title = "Saurav"
publishDir = "public"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Saurav"

[params]
    author = "Saurav Pandey"
    description = "Saurav'sPortfolio"
    keywords = "blog,developer,personal"
    info = "Senior Backend Engineer \n / Data Science Professional"
    avatarurl = "pp.jpg"
    #gravatar = "pysaurav@gmail.com"
    footercontent = "Express Yourself!"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"
    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/pysaurav/"
[[params.social]]
    name = "ResearchGate"
    icon = "fa-brands fa-researchgate fa-2x"
    weight = 2
    url = "https://www.researchgate.net/profile/Saurav_Pandey"
[[params.social]]
    name = "Twitter"
    icon = "fa-brands fa-x-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/pysaurav/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/pysaurav/"
[[params.social]]
    name = "Medium"
    icon = "fa-brands fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@pysaurav"
[[params.social]]
    name = "mail"
    icon = "fa fa-envelope fa-2x"
    weight = 6
    url = "mailto:pysaurav@gmail.com"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "DataScience"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 3
            url = "random/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 4
            url = "contact/"

    [languages.no]
        languagename = "Norsk"

        [languages.no.menu]

            [[languages.no.menu.main]]
            name = "Om"
            weight = 1
            url = "about/"

            [[languages.no.menu.main]]
            name = "DataScience"
            weight = 2
            url = "posts/"

            [[languages.no.menu.main]]
            name = "Blogg"
            weight = 3
            url = "random/"

            [[languages.no.menu.main]]
            name = "Kontakt"
            weight = 4
            url = "contact/"
    
    